controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    
    
    panda_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    panda_hand_controller:
      type: position_controllers/GripperActionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_group_velocity_controller:
      type: forward_command_controller/JointGroupVelocityController
    
    
    moveit_franka_controller:
      type: franka_example_controllers/JointVelocityMoveItController
    
    


# 控制器参数
moveit_franka_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    planning_group: "panda_arm"
    arm_id: "panda"
    ee_pose_topic: "/fd/ee_pose"
    ik_timeout: 0.2
    max_joint_velocity: 0.5


panda_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7

joint_group_velocity_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7

panda_hand_controller:
  ros__parameters:
    joint: panda_finger_joint1
